const columns = [
  { title: "Explore", links: ["Rooms", "Experiences", "Gorilla permits", "Gift cards"] },
  { title: "Resort", links: ["About us", "Careers", "Community projects", "Sustainability"] },
  { title: "Support", links: ["Help centre", "Cancellations", "Travel advice", "FAQ"] },
];

function InstagramIcon(){return <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.8"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg>}
function FacebookIcon(){return <svg viewBox="0 0 24 24" width="18" height="18" fill="currentColor"><path d="M13.7 21v-8h2.7l.4-3.1h-3.1v-2c0-.9.3-1.5 1.6-1.5H17V3.6c-.3 0-1.4-.1-2.5-.1-2.5 0-4.2 1.5-4.2 4.3v2.1H7.5V13h2.8v8h3.4z"/></svg>}
function CheckIcon(){return <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 12.5l4 4L19 7"/></svg>}
function XIcon(){return <svg viewBox="0 0 24 24" width="17" height="17" fill="currentColor"><path d="M18.9 3H22l-6.8 7.8L23.2 21H17l-4.9-6.4L6.5 21H3.4l7.2-8.3L2.9 3H9l4.4 5.8L18.9 3zm-1.1 16.2h1.7L8 4.7H6.2l11.6 14.5z"/></svg>}
const socials=[{label:"Instagram",icon:<InstagramIcon/>},{label:"Facebook",icon:<FacebookIcon/>},{label:"X / Twitter",icon:<XIcon/>}];

export default function Footer() {
  return <footer className="bg-tide-900 pt-16 text-sand-100"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-10 px-6 pb-14 sm:grid-cols-3 lg:grid-cols-5 lg:px-10"><div className="col-span-2 lg:col-span-2"><div className="flex items-center gap-3"><img src="/logo.jpg" alt="Gorilla Recreational Resort crest" className="h-10 w-10 shrink-0 rounded-full object-cover ring-2 ring-gold-400/60"/><span className="font-display text-lg font-semibold text-sand-50">Gorilla Recreational Resort</span></div><p className="mt-4 max-w-xs text-sm leading-relaxed text-sand-100/60">Five rooms named for five volcanoes, at the foot of Volcanoes National Park in Musanze, Rwanda — Musanganya Faustin Ese.</p><div className="mt-6 flex gap-3">{socials.map(s=><a key={s.label} href="#top" aria-label={s.label} title={s.label} className="grid h-10 w-10 place-items-center rounded-full border border-sand-50/20 text-sand-100/80 transition hover:border-gold-300 hover:bg-gold-300/10 hover:text-gold-300">{s.icon}</a>)}</div></div>{columns.map(column=><div key={column.title}><h3 className="text-xs font-semibold uppercase tracking-widest2 text-sand-100/50">{column.title}</h3><ul className="mt-4 flex flex-col gap-3">{column.links.map(link=><li key={link}><a href={link==="Rooms"?"/rooms":"/#top"} className="text-sm text-sand-100/75 transition hover:text-sand-50">{link}</a></li>)}</ul></div>)}<div><h3 className="text-xs font-semibold uppercase tracking-widest2 text-sand-100/50">Contact</h3><ul className="mt-4 flex flex-col gap-3 text-sm text-sand-100/75"><li>Kinigi Road, Musanze, Rwanda</li><li><a href="mailto:resortgorilla@gmail.com" className="hover:text-sand-50">resortgorilla@gmail.com</a></li><li>+250 786 227 645</li></ul></div></div><div className="border-t border-sand-50/10 px-6 py-6 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-3 text-xs text-sand-100/50 sm:flex-row"><p>© {new Date().getFullYear()} Gorilla Recreational Resort, Musanze. All rights reserved.</p><div className="flex flex-wrap gap-5"><a href="#top" className="hover:text-sand-100">Privacy</a><a href="#top" className="hover:text-sand-100">Terms</a><a href="/manager" aria-label="Manager login" title="Manager login" className="inline-flex items-center gap-2 transition hover:text-gold-300"><span className="grid h-7 w-7 place-items-center rounded-full border border-gold-300/50 text-gold-300 transition hover:bg-gold-300/10"><CheckIcon /></span><span>Manager login</span></a></div></div></div></footer>;
}
